# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = heap.o
LINKOBJ  = heap.o
LIBS     = -L"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/lib" -L"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/include" -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/include" -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/MODERN/DSA/Project/crow/include"
BIN      = heapsort.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

heap.o: heap.cpp
	$(CPP) -c heap.cpp -o heap.o $(CXXFLAGS)
