# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Assign6.o
LINKOBJ  = Assign6.o
LIBS     = -L"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/lib" -L"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/include" -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/include" -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/MODERN/DSA/Practicals/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/MODERN/DSA/Project/crow/include"
BIN      = Assign6.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Assign6.o: Assign6.cpp
	$(CPP) -c Assign6.cpp -o Assign6.o $(CXXFLAGS)
